### ISSUE TITLE
Create task template for software tasks

### ISSUE THREAD

**Issue by AksonovSergei** [KPI-Rover/KPI-Rover.github.io#10]
I found more interesting solution. We can create common templates that will be used in all our repositories.
# Setting Up Organization-Wide Issue Templates in GitHub

GitHub allows organizations to create standardized issue templates that can be used across all repositories in the organization. This helps maintain consistency in issue reporting and makes it easier for contributors to provide the necessary information.

## Prerequisites

- You must be an organization owner or have admin permissions for the organization.
- Your organization must be using GitHub Team or GitHub Enterprise plan.

## Creating Organization-Wide Issue Templates

1. **Navigate to the Organization Settings**:
   - Go to your organization's main page (`https://github.com/your-organization-name`).
   - Click on "Settings" in the top navigation bar.

2. **Access the Repository Templates Section**:
   - In the left sidebar, click on "Repository" and then select "Template repositories".

3. **Create a Special Repository**:
   - Create a new repository named `.github` in your organization.
   - This repository will store organization-wide settings, including issue templates.

4. **Add Issue Templates**:
   - Inside the `.github` repository, create a directory called `ISSUE_TEMPLATE`.
   - Inside this directory, create your issue template files.

5. **Template File Formats**:
   - You can use either Markdown (`.md`) files or YAML (`.yml` or `.yaml`) files.
   - YAML format is recommended for form-based templates.

## Example Template Structure

```
organization-name/.github/
└── ISSUE_TEMPLATE/
    ├── bug_report.md
    ├── feature_request.md
    └── config.yml
```

## Example YAML Template for Bug Reports

```yaml
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
```

## Example Markdown Template for Feature Requests

```markdown
---
name: Feature request
about: Suggest an idea for this project
title: "[FEATURE]"
labels: enhancement
assignees: ''
---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```

## Configuration File

You can also add a `config.yml` file in the `.github/ISSUE_TEMPLATE` directory to customize the issue template selector:

```yaml
blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
```

## Repository-Specific vs. Organization-Wide Templates

- If a repository has its own issue templates, those will be displayed alongside the organization-wide templates.
- Contributors can choose which template to use when creating a new issue.
- Repository-specific templates take precedence over organization-wide templates with the same name.

## Best Practices

1. **Keep Templates Concise**: Make sure templates are easy to fill out and not too lengthy.
2. **Use Clear Labels**: Add relevant labels to automatically categorize issues.
3. **Regular Maintenance**: Review and update templates periodically based on feedback.
4. **Provide Examples**: Include examples in template fields to guide users.
5. **Consider Multiple Formats**: Provide both simple and detailed templates for different types of issues.
